apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    application: kube-aws-autoscaler
    version: v0.7.1
  name: kube-aws-autoscaler
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      application: kube-aws-autoscaler
  template:
    metadata:
      labels:
        application: kube-aws-autoscaler
        version: 0.0.1
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/role
                operator: In
                values:
                - master
      tolerations:
      - key: dedicated
        operator: Equal
        value: master
        effect: NoSchedule
      containers:
      - name: autoscaler
        image: 971383676178.dkr.ecr.us-east-1.amazonaws.com/kube-aws-autoscaler:[tag]
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 50Mi
        args:
        - "--asg"
        - "asg group name"
