apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    application: kube-aws-autoscaler
    version: v0.0.1
  name: kube-aws-autoscaler
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      application: kube-aws-autoscaler
  template:
    metadata:
      labels:
        application: kube-aws-autoscaler
        version: v0.0.1
      annotations:
    spec:
      containers:
      - name: autoscaler
        image: 971383676178.dkr.ecr.us-east-1.amazonaws.com/kube-aws-autoscaler:0.7-2-gf9ea901-dirty
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 50Mi
        args:
        - "--debug"
        - "--asg"
        - "tf-asg-20170112181758063213024i4h"
        - "--buffer-cpu-percentage"
        - "50"
